-- ==============================================================================
-- SALESCARE CRM V6 - FULL ONLINE SUPABASE SCHEMA (OPTION A)
-- This script creates all 26 tables for 100% online mode.
-- ==============================================================================

-- 1. EXTENSIONS & FUNCTIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to handle new user registration from Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.user_profiles (id, email, name, role)
  VALUES (new.id, new.email, split_part(new.email, '@', 1), 'STAFF');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. CORE TABLES (IF NOT EXISTS to protect existing data)
CREATE TABLE IF NOT EXISTS public.shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  type TEXT,
  phone TEXT,
  address TEXT,
  logo_url TEXT,
  status TEXT DEFAULT 'active',
  owner_user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  role TEXT DEFAULT 'STAFF', 
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.user_profiles(id),
  shop_id BIGINT REFERENCES public.shops(id),
  role TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.shop_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  invoice_prefix TEXT DEFAULT 'INV',
  auto_generate_invoice_code BOOLEAN DEFAULT true,
  allow_negative_stock BOOLEAN DEFAULT false,
  deduct_stock_on_invoice_save BOOLEAN DEFAULT false,
  deduct_stock_on_paid_status BOOLEAN DEFAULT true,
  allow_edit_invoice_after_stock_deducted BOOLEAN DEFAULT false,
  low_stock_default_threshold INTEGER DEFAULT 10,
  expiry_warning_days INTEGER DEFAULT 30,
  notification_settings JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CRM & BUSINESS TABLES
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_code TEXT,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  source TEXT,
  status TEXT,
  lead_temperature TEXT,
  tags TEXT[],
  assigned_to UUID REFERENCES public.user_profiles(id),
  start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_purchase_date TIMESTAMP WITH TIME ZONE,
  expected_repurchase_date TIMESTAMP WITH TIME ZONE,
  total_revenue NUMERIC DEFAULT 0,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  order_code TEXT NOT NULL,
  customer_id BIGINT REFERENCES public.customers(id),
  order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  payment_date TIMESTAMP WITH TIME ZONE,
  subtotal NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  total_amount NUMERIC DEFAULT 0,
  paid_amount NUMERIC DEFAULT 0,
  debt_amount NUMERIC DEFAULT 0,
  payment_method TEXT,
  payment_status TEXT,
  order_status TEXT,
  stock_status TEXT,
  stock_deducted_at TIMESTAMP WITH TIME ZONE,
  stock_returned_at TIMESTAMP WITH TIME ZONE,
  expected_repurchase_date TIMESTAMP WITH TIME ZONE,
  repurchase_cycle_days INTEGER,
  post_purchase_reminder_type TEXT,
  post_purchase_reminder_date TIMESTAMP WITH TIME ZONE,
  post_purchase_reminder_note TEXT,
  reminder_status TEXT,
  assigned_to UUID REFERENCES public.user_profiles(id),
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT,
  sku TEXT,
  item_name TEXT,
  quantity INTEGER DEFAULT 1,
  unit_price NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  line_total NUMERIC DEFAULT 0,
  stock_deducted BOOLEAN DEFAULT false,
  deducted_quantity INTEGER DEFAULT 0,
  stock_deducted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  name TEXT NOT NULL,
  sku TEXT,
  barcode TEXT,
  brand TEXT,
  category TEXT,
  stock_quantity INTEGER DEFAULT 0,
  unit TEXT,
  import_price NUMERIC DEFAULT 0,
  selling_price NUMERIC DEFAULT 0,
  expiry_date TIMESTAMP WITH TIME ZONE,
  import_date TIMESTAMP WITH TIME ZONE,
  supplier TEXT,
  low_stock_threshold INTEGER DEFAULT 5,
  repurchase_cycle_days INTEGER,
  status TEXT DEFAULT 'active',
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  product_id BIGINT REFERENCES public.products(id),
  sku TEXT,
  type TEXT,
  quantity INTEGER,
  before_quantity INTEGER,
  after_quantity INTEGER,
  related_order_id BIGINT,
  related_stocktake_id BIGINT,
  created_by UUID REFERENCES public.user_profiles(id),
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  service_name TEXT,
  appointment_date TIMESTAMP WITH TIME ZONE,
  start_time TEXT,
  end_time TEXT,
  staff_id UUID REFERENCES public.user_profiles(id),
  room TEXT,
  status TEXT DEFAULT 'pending',
  reminder_before TEXT,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  order_id BIGINT REFERENCES public.orders(id),
  appointment_id BIGINT REFERENCES public.appointments(id),
  assigned_to UUID REFERENCES public.user_profiles(id),
  reminder_type TEXT,
  title TEXT,
  note TEXT,
  remind_at TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'pending',
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  order_id BIGINT REFERENCES public.orders(id),
  type TEXT,
  content TEXT,
  created_by UUID REFERENCES public.user_profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  user_id UUID REFERENCES public.user_profiles(id),
  reminder_id BIGINT REFERENCES public.reminders(id),
  title TEXT,
  message TEXT,
  status TEXT DEFAULT 'unread',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  read_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.message_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  title TEXT,
  content TEXT,
  type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Spa & Clinic Tables
CREATE TABLE IF NOT EXISTS public.skin_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  skin_type TEXT,
  skin_concerns TEXT[],
  severity TEXT,
  current_products TEXT,
  irritation_products TEXT,
  allergies TEXT,
  contraindications TEXT,
  previous_services TEXT,
  goals TEXT,
  professional_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.treatment_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  package_name TEXT,
  service_name TEXT,
  total_sessions INTEGER,
  used_sessions INTEGER DEFAULT 0,
  remaining_sessions INTEGER,
  start_date TIMESTAMP WITH TIME ZONE,
  expiry_date TIMESTAMP WITH TIME ZONE,
  assigned_to UUID REFERENCES public.user_profiles(id),
  status TEXT DEFAULT 'active',
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.treatment_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  package_id BIGINT REFERENCES public.treatment_packages(id),
  customer_id BIGINT REFERENCES public.customers(id),
  session_date TIMESTAMP WITH TIME ZONE,
  service_name TEXT,
  staff_id UUID REFERENCES public.user_profiles(id),
  note TEXT,
  status TEXT DEFAULT 'completed',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.before_after_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  order_id BIGINT REFERENCES public.orders(id),
  treatment_package_id BIGINT REFERENCES public.treatment_packages(id),
  treatment_session_id BIGINT REFERENCES public.treatment_sessions(id),
  image_url TEXT,
  image_type TEXT,
  treatment_area TEXT,
  capture_date TIMESTAMP WITH TIME ZONE,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Loyalty & Promos
CREATE TABLE IF NOT EXISTS public.loyalty_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  points INTEGER DEFAULT 0,
  total_earned INTEGER DEFAULT 0,
  total_redeemed INTEGER DEFAULT 0,
  membership_tier TEXT DEFAULT 'MEMBER',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.loyalty_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id),
  type TEXT,
  points INTEGER,
  reason TEXT,
  order_id BIGINT REFERENCES public.orders(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  code TEXT UNIQUE NOT NULL,
  customer_id BIGINT REFERENCES public.customers(id),
  discount_type TEXT,
  discount_value NUMERIC,
  expiry_date TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Utilities
CREATE TABLE IF NOT EXISTS public.stocktakes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  title TEXT,
  status TEXT DEFAULT 'pending',
  created_by UUID REFERENCES public.user_profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.stocktake_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  stocktake_id BIGINT REFERENCES public.stocktakes(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  sku TEXT,
  product_name TEXT,
  system_quantity INTEGER,
  actual_quantity INTEGER,
  difference INTEGER,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.login_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.user_profiles(id),
  ip_address TEXT,
  user_agent TEXT,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==============================================================================
-- 4. APPLY ROW LEVEL SECURITY (RLS) FOR MULTI-TENANCY
-- By default, all users will only be able to view/edit data that belongs to their shop_id
-- Super Admins bypass this.
-- ==============================================================================

-- Helper function to check if user has access to shop
CREATE OR REPLACE FUNCTION public.user_has_shop_access(check_shop_id BIGINT)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_shops 
    WHERE user_id = auth.uid() AND shop_id = check_shop_id
  ) OR EXISTS (
    SELECT 1 FROM public.user_profiles 
    WHERE id = auth.uid() AND role = 'SUPER_ADMIN'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enable RLS on all tables
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN 
    SELECT table_name FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
  END LOOP;
END
$$;

-- Create Policies for Shop-based access
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN 
    SELECT table_name FROM information_schema.columns 
    WHERE column_name = 'shop_id' AND table_schema = 'public' AND table_name != 'user_shops'
  LOOP
    -- SELECT
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Select on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Select on %I" ON public.%I FOR SELECT USING (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
    
    -- INSERT
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Insert on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Insert on %I" ON public.%I FOR INSERT WITH CHECK (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
    
    -- UPDATE
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Update on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Update on %I" ON public.%I FOR UPDATE USING (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
    
    -- DELETE
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Delete on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Delete on %I" ON public.%I FOR DELETE USING (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
  END LOOP;
END
$$;

-- Helper functions to avoid infinite recursion
CREATE OR REPLACE FUNCTION public.get_auth_user_role()
RETURNS text AS $$
DECLARE
  user_role text;
BEGIN
  SELECT role INTO user_role FROM public.user_profiles WHERE id = auth.uid();
  RETURN user_role;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Special Policies for Auth related tables
DROP POLICY IF EXISTS "Users can view their own profile" ON public.user_profiles;
CREATE POLICY "Users can view their own profile" ON public.user_profiles FOR SELECT USING (
  id = auth.uid() OR public.get_auth_user_role() IN ('SUPER_ADMIN', 'SHOP_OWNER')
);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.user_profiles;
CREATE POLICY "Users can update their own profile" ON public.user_profiles FOR UPDATE USING (id = auth.uid());

DROP POLICY IF EXISTS "Users can view user_shops" ON public.user_shops;
CREATE POLICY "Users can view user_shops" ON public.user_shops FOR SELECT USING (user_id = auth.uid() OR EXISTS (SELECT 1 FROM public.user_profiles up WHERE up.id = auth.uid() AND up.role = 'SUPER_ADMIN'));

-- Trigger attachment
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
