-- PATCH V10: Thêm bảng Quản lý Dịch vụ (Services)
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  name TEXT NOT NULL,
  code TEXT,
  category TEXT,
  price NUMERIC DEFAULT 0,
  duration_minutes INTEGER DEFAULT 60,
  status TEXT DEFAULT 'active',
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- BẬT RLS
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- CẤP QUYỀN RLS
DROP POLICY IF EXISTS "Tenant Isolation Select on services" ON public.services;
CREATE POLICY "Tenant Isolation Select on services" ON public.services FOR SELECT USING (public.user_has_shop_access(shop_id));

DROP POLICY IF EXISTS "Tenant Isolation Insert on services" ON public.services;
CREATE POLICY "Tenant Isolation Insert on services" ON public.services FOR INSERT WITH CHECK (public.user_has_shop_access(shop_id));

DROP POLICY IF EXISTS "Tenant Isolation Update on services" ON public.services;
CREATE POLICY "Tenant Isolation Update on services" ON public.services FOR UPDATE USING (public.user_has_shop_access(shop_id));

DROP POLICY IF EXISTS "Tenant Isolation Delete on services" ON public.services;
CREATE POLICY "Tenant Isolation Delete on services" ON public.services FOR DELETE USING (public.user_has_shop_access(shop_id));

NOTIFY pgrst, 'reload schema';
