-- PATCH V9: Di chuyển các bảng dành riêng cho Khách Hàng từ Local DB lên Supabase & Bổ sung QR Code

-- 1. Bảng Hồ sơ làn da (Skin Profiles)
CREATE TABLE IF NOT EXISTS public.skin_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
  skin_type TEXT DEFAULT 'Da thường',
  skin_concerns TEXT[] DEFAULT '{}',
  severity TEXT DEFAULT 'Nhẹ',
  current_products TEXT,
  irritation_products TEXT,
  allergies TEXT,
  contraindications TEXT,
  previous_services TEXT,
  goals TEXT,
  professional_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Bảng Gói Liệu trình (Treatment Packages)
CREATE TABLE IF NOT EXISTS public.treatment_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
  package_name TEXT NOT NULL,
  service_name TEXT NOT NULL,
  total_sessions INTEGER NOT NULL DEFAULT 1,
  used_sessions INTEGER NOT NULL DEFAULT 0,
  remaining_sessions INTEGER NOT NULL DEFAULT 1,
  start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expiry_date TIMESTAMP WITH TIME ZONE,
  assigned_to UUID REFERENCES public.user_profiles(id),
  status TEXT DEFAULT 'Đang hoạt động',
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Bảng Các Buổi Liệu Trình (Treatment Sessions)
CREATE TABLE IF NOT EXISTS public.treatment_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  package_id BIGINT REFERENCES public.treatment_packages(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
  session_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  service_name TEXT NOT NULL,
  staff_id UUID REFERENCES public.user_profiles(id),
  note TEXT,
  status TEXT DEFAULT 'Đã làm',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Bảng Ảnh Before/After (Before After Images)
CREATE TABLE IF NOT EXISTS public.before_after_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES public.shops(id),
  customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  image_type TEXT DEFAULT 'before',
  treatment_area TEXT,
  capture_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Bổ sung cấu hình QR Code và tài khoản ngân hàng vào shop_settings
ALTER TABLE public.shop_settings
ADD COLUMN IF NOT EXISTS bank_account_name TEXT,
ADD COLUMN IF NOT EXISTS bank_account_number TEXT,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS qr_code_url TEXT;

-- BẬT RLS (Row Level Security) CHO CÁC BẢNG MỚI
ALTER TABLE public.skin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.before_after_images ENABLE ROW LEVEL SECURITY;

-- CẤP QUYỀN RLS
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN 
    SELECT unnest(ARRAY['skin_profiles', 'treatment_packages', 'treatment_sessions', 'before_after_images'])
  LOOP
    -- SELECT
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Select on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Select on %I" ON public.%I FOR SELECT USING (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
    
    -- INSERT
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Insert on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Insert on %I" ON public.%I FOR INSERT WITH CHECK (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
    
    -- UPDATE
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Update on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Update on %I" ON public.%I FOR UPDATE USING (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
    
    -- DELETE
    EXECUTE format('
      DROP POLICY IF EXISTS "Tenant Isolation Delete on %I" ON public.%I;
      CREATE POLICY "Tenant Isolation Delete on %I" ON public.%I FOR DELETE USING (public.user_has_shop_access(shop_id));
    ', t, t, t, t);
  END LOOP;
END
$$;

NOTIFY pgrst, 'reload schema';
