-- ==============================================================================
-- SALESCARE CRM V6 - MIGRATION SCRIPT TO SUPABASE
-- Run this script in the Supabase SQL Editor to initialize your online database.
-- ==============================================================================

-- 1. Create shops table
CREATE TABLE shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  type TEXT,
  phone TEXT,
  address TEXT,
  logo_url TEXT,
  status TEXT DEFAULT 'active',
  owner_user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create users profile table (linked to auth.users)
CREATE TABLE user_profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  role TEXT DEFAULT 'STAFF', -- SUPER_ADMIN, SHOP_OWNER, MANAGER, SALES, STAFF
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create user_shops mapping (Multi-tenant)
CREATE TABLE user_shops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES user_profiles(id),
  shop_id BIGINT REFERENCES shops(id),
  role TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Customers table
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT REFERENCES shops(id),
  customer_code TEXT,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  source TEXT,
  status TEXT,
  lead_temperature TEXT,
  tags TEXT[],
  assigned_to UUID REFERENCES user_profiles(id),
  total_revenue NUMERIC DEFAULT 0,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create IP Log tracking
CREATE TABLE login_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES user_profiles(id),
  ip_address TEXT,
  user_agent TEXT,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can view their own profile
CREATE POLICY "Users can view their own profile" ON user_profiles
  FOR SELECT USING (id = auth.uid());

-- Users can only see shops they belong to
CREATE POLICY "Users can view their own shops" ON shops
  FOR SELECT USING (
    id IN (SELECT shop_id FROM user_shops WHERE user_id = auth.uid()) OR auth.uid() IN (SELECT id FROM user_profiles WHERE role = 'SUPER_ADMIN')
  );

-- Users can only view customers in their shop
CREATE POLICY "Users can view customers in their shop" ON customers
  FOR SELECT USING (
    shop_id IN (SELECT shop_id FROM user_shops WHERE user_id = auth.uid())
  );

-- ==============================================================================
-- 6. Trigger to automatically create a user profile when a new user signs up
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.user_profiles (id, email, name, role)
  VALUES (new.id, new.email, split_part(new.email, '@', 1), 'STAFF');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==============================================================================
-- EDGE FUNCTION FOR EMAIL ALERT ON NEW IP LOGIN
-- To use this, you must create a Supabase Edge Function:
-- supabase functions new login-alert
-- ==============================================================================
