-- Kịch bản tạo bảng cho Supabase (SalesCare CRM)

-- 1. Bảng Khách hàng (Customers)
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  source TEXT DEFAULT 'Facebook',
  lead_temperature TEXT DEFAULT 'Nóng',
  status TEXT DEFAULT 'Khách mới',
  note TEXT,
  tags TEXT[] DEFAULT '{}',
  assigned_to TEXT DEFAULT 'admin',
  expected_repurchase_date DATE,
  start_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Hóa đơn (Orders)
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  order_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  amount NUMERIC NOT NULL,
  purchase_date DATE NOT NULL,
  repurchase_cycle_days INTEGER,
  post_purchase_reminder_type TEXT,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Nhắc hẹn (Reminders)
CREATE TABLE reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  assigned_to TEXT DEFAULT 'admin',
  reminder_type TEXT NOT NULL,
  title TEXT NOT NULL,
  note TEXT,
  remind_at TIMESTAMPTZ NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bảng Mẫu tin nhắn (Message Templates)
CREATE TABLE message_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bật Realtime cho các bảng cốt lõi
alter publication supabase_realtime add table customers;
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table reminders;
alter publication supabase_realtime add table message_templates;

-- ==========================================
-- GIAI ĐOẠN MỞ RỘNG V3 (SPA / CLINIC / COSMETIC)
-- ==========================================

-- 5. Bảng Hồ sơ làn da (Skin Profiles)
CREATE TABLE skin_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  skin_type TEXT NOT NULL,
  skin_concerns TEXT[] DEFAULT '{}',
  severity TEXT,
  current_products TEXT,
  irritation_products TEXT,
  allergies TEXT,
  contraindications TEXT,
  previous_services TEXT,
  goals TEXT,
  professional_note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Bảng Lịch hẹn (Appointments)
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  service_name TEXT NOT NULL,
  appointment_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  staff_id TEXT,
  room TEXT,
  status TEXT DEFAULT 'Đã đặt',
  reminder_before TEXT DEFAULT 'Không nhắc',
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Bảng Gói Liệu trình (Treatment Packages)
CREATE TABLE treatment_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  package_name TEXT NOT NULL,
  service_name TEXT NOT NULL,
  total_sessions INTEGER NOT NULL,
  used_sessions INTEGER DEFAULT 0,
  remaining_sessions INTEGER NOT NULL,
  start_date DATE NOT NULL,
  expiry_date DATE,
  assigned_to TEXT,
  status TEXT DEFAULT 'Đang hoạt động',
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Bảng Buổi liệu trình (Treatment Sessions)
CREATE TABLE treatment_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT REFERENCES treatment_packages(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  session_date DATE NOT NULL,
  service_name TEXT NOT NULL,
  staff_id TEXT,
  note TEXT,
  status TEXT DEFAULT 'Đã làm',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Bảng Ảnh Before/After (Before After Images)
CREATE TABLE before_after_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  treatment_package_id BIGINT REFERENCES treatment_packages(id) ON DELETE SET NULL,
  treatment_session_id BIGINT REFERENCES treatment_sessions(id) ON DELETE SET NULL,
  image_url TEXT NOT NULL,
  image_type TEXT NOT NULL, -- before, after, progress
  treatment_area TEXT,
  capture_date DATE NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Bảng Kho Sản phẩm (Products)
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT UNIQUE NOT NULL,
  brand TEXT,
  category TEXT NOT NULL,
  stock_quantity INTEGER DEFAULT 0,
  unit TEXT DEFAULT 'Hộp',
  import_price NUMERIC DEFAULT 0,
  selling_price NUMERIC DEFAULT 0,
  expiry_date DATE,
  supplier TEXT,
  low_stock_threshold INTEGER DEFAULT 5,
  repurchase_cycle_days INTEGER,
  status TEXT DEFAULT 'Còn hàng',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Bảng Giao dịch Kho (Inventory Transactions)
CREATE TABLE inventory_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- import, export, sale, return, adjustment
  quantity INTEGER NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Bảng Tích điểm (Loyalty Points)
CREATE TABLE loyalty_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE UNIQUE,
  points INTEGER DEFAULT 0,
  total_earned INTEGER DEFAULT 0,
  total_redeemed INTEGER DEFAULT 0,
  membership_tier TEXT DEFAULT 'Thường',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Bảng Lịch sử Tích điểm (Loyalty Transactions)
CREATE TABLE loyalty_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- earn, redeem
  points INTEGER NOT NULL,
  reason TEXT,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Bảng Voucher
CREATE TABLE vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  discount_type TEXT NOT NULL, -- percent, fixed
  discount_value NUMERIC NOT NULL,
  expiry_date DATE NOT NULL,
  status TEXT DEFAULT 'Khả dụng',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. Bảng Biểu mẫu đồng ý (Consent Forms)
CREATE TABLE consent_forms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  form_type TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  related_service TEXT,
  signature_url TEXT,
  signed_at TIMESTAMPTZ,
  created_by TEXT,
  status TEXT DEFAULT 'Chưa ký',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. Bảng Trợ lý AI (AI Suggestions)
CREATE TABLE ai_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  suggestion_type TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'Chưa xử lý',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bật Realtime cho các bảng v3 (Nếu cần)
alter publication supabase_realtime add table appointments;
alter publication supabase_realtime add table treatment_packages;
alter publication supabase_realtime add table products;

-- ==========================================
-- GIAI ĐOẠN MỞ RỘNG V4 (REVENUE, INVENTORY, EXCEL)
-- ==========================================

-- 17. Bảng Chi tiết Hóa đơn (Order Items)
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  sku TEXT,
  item_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC NOT NULL,
  discount NUMERIC DEFAULT 0,
  line_total NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bổ sung cột cho bảng orders (V4 Update)
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_date DATE;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC DEFAULT 0;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount NUMERIC DEFAULT 0;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_amount NUMERIC DEFAULT 0;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS debt_amount NUMERIC DEFAULT 0;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'Tiền mặt';
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'Chưa thanh toán';
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_status TEXT DEFAULT 'Hoàn thành';
-- Ghi chú: Vì Supabase schema thường được chạy từ đầu, phần này có thể cập nhật trực tiếp vào định nghĩa CREATE TABLE orders ở trên. (Tôi sẽ để dưới dạng ALTER cho dễ quản lý các dự án đã chạy).

-- 18. Bảng Phiên kiểm kê (Stocktakes)
CREATE TABLE stocktakes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_by TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 19. Bảng Chi tiết Kiểm kê (Stocktake Items)
CREATE TABLE stocktake_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stocktake_id BIGINT REFERENCES stocktakes(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  product_name TEXT NOT NULL,
  system_quantity INTEGER NOT NULL,
  actual_quantity INTEGER NOT NULL,
  difference INTEGER NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 20. Bảng Lịch sử Import (Import Logs)
CREATE TABLE import_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_type TEXT NOT NULL,
  file_name TEXT NOT NULL,
  total_rows INTEGER DEFAULT 0,
  success_rows INTEGER DEFAULT 0,
  error_rows INTEGER DEFAULT 0,
  status TEXT DEFAULT 'success',
  error_detail TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
